#!/bin/sh

. ./globals

[ "$?" -ne "0" ] && { echo "Globals file not found. Is your local git tree ok?" && echo && exit 1; }


# Globals

origdir=$(realpath $(pwd))

CHLVER=$(dpkg-parsechangelog --file $origdir/changelog --show-field Version)

builddir="$origdir/$APPNAME-$CHLVER"


# Main

echo "Cleaning up …"

rm -rf $builddir $origdir/$APPNAME_*.*

echo
echo "Ok."
echo
